macro(vu8_plugin _name _sources)
    add_library(vu8_${_name} SHARED ${_sources})
    target_link_libraries(vu8_${_name} ${V8_LIB_DYNAMIC})
    add_dependencies(vu8_${_name} buildextv8)
    install(TARGETS vu8_${_name} DESTINATION ${VU8_PLUGIN_PATH})
endmacro()
